config/routes.rb
Rails.application.routes.draw do

    devise_for :profs, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'profs/omniauth_callbacks'}
    #devise_for :technicals, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'technicals/omniauth_callbacks'}

    scope '(:locale)' do

      devise_for :profs, skip: :omniauth_callbacks, controllers: {
        registrations: 'profs/registrations',
        confirmations: 'profs/confirmations',
      }

      devise_for :technicals, controllers: {
        registrations: 'technicals/registrations',
        confirmations: 'technicals/confirmations',
        sessions: 'technicals/sessions',
      }

      devise_for :admins, controllers: {
        registrations: 'admins/registrations'
      }

      namespace :technical do
        get 'dashboard/index'
        resources :tools, only: [:index, :show] do
          resources :labs, only: [:index] do
            resources :reportings, only: [:new, :create, :show, :edit, :update, :destroy]
          end
        end
        resources :labs, only: [:show]
        resources :reportings, only: [:index]
        resources :requests
        resources :books, only: [:destroy]
      end

      namespace :admin do
        resources :tools do
          resources :documentations, only: [:destroy]
          resources :photos, only: [:destroy]
          resources :books, only: [:index]
        end
        resources :labs do
          resources :lab_technicals, only: [:new, :create, :edit, :update]
        end
        resources :technicals, only: [:index, :show] do
          resources :lab_technicals, only: [:new, :create, :edit, :update]
        end
        resources :requests, only: [:index, :show, :update, :destroy]
        resources :categories
        resources :lab_technicals, only: [:destroy]
        resources :books, only: [:update, :destroy]
        get 'dashboard/index'
        get 'tools/choose/:id(.:format)', :to => 'tools#choose', as: "choose_tool_route"
        get 'labs/assign/:id(.:format)', :to => 'labs#assign', as: "assign_lab_route"
        get 'labs/assign_update/:id/:tool(.:splat)', :to => 'labs#assign_update', as: "assign_update_lab_route"
        post 'authorize/:id(.:format)', :to => 'dashboard#authorize', as: "authorize_route"
        post 'confirm/:id(.:format)', :to => 'dashboard#confirm', as: "confirm_route"
        post 'htmlcreate(.:format)', :to => 'categories#htmlcreate', as: "htmlcreate_route"
        delete 'deleteprof/:id(.:format)', :to => 'dashboard#deleteprof', as: "deleteprof_route"
        post 'reportings/dismiss/:id(.:format)', :to => 'reportings#dismiss', as: "dismiss_route"
        post 'reportings/fix/:id(.:format)', :to => 'reportings#fix', as: "fix_route"
        post 'reportings/replace/:id(.:format)', :to => 'reportings#replace', as: "replace_route"
      end

      post 'avaiable/:tool_id(.:format)', :to => 'tempbooks#avaiable', as: "avaiable_route"
      resources :tools, only: [:index, :show] do
        resources :tempbooks, only: [:new, :create]
        resources :posts, only: [:create, :edit, :update, :destroy]
      end
      resources :categories, only: [:create]
      resources :requests, only: [:new, :create, :index, :show]
      resources :books, only: [:index]

      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
      root to: "home#index"
      #resources :schools
    end
end

app/models/tool.rb
class ToolValidator < ActiveModel::Validator
  def validate(record)

    if record.identifier.present? && record.quantity.present?
      if record.quantity > 1
        record.errors[:base] << I18n.t('tools.identifier')
      end
    end

    if record.quantity.present?
      if record.quantity < 0
        record.errors[:base] << I18n.t('tools.quantity')
      end
    end

  end
end

class Tool < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  mount_uploader :photo, PhotoUploader
  process_in_background :photo
  translates :name, :description
  validates :name, presence: true
  validates :identifier, uniqueness: true, :allow_blank => true
  validates :description, presence: true
  validates :quantity, presence: true, format: {with: /([0-9]+)/}
  has_and_belongs_to_many :labs
  validates_each :labs do |tool, attr, value|
    if tool.quantity.present?
      tool.errors.add attr, I18n.t('.tools.labs') if tool.labs.size > tool.quantity
    end
    tool.errors.add attr, I18n.t('.tools.nolabs') if tool.labs.size < 1
  end
  has_and_belongs_to_many :categories
  has_many :tempbooks
  has_many :books, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :reportings, dependent: :destroy
  has_many :documentations, dependent: :destroy
  accepts_nested_attributes_for :documentations, allow_destroy: true
  has_many :photos, dependent: :destroy
  validates_each :photos do |tool, attr, value|
   tool.errors.add attr, I18n.t('.tools.photos') if tool.photos.size > 4
  end
  accepts_nested_attributes_for :photos, allow_destroy: true
  before_save :name

#  default_scope -> {order(name: :asc)}
  #default_scope with_translations.order("name ASC")

  validates_with ToolValidator
  paginates_per 12

  def name=(s)
    write_attribute(:name, s.to_s.capitalize)
  end
  def self.with_translated_name(name_string)
  with_translations(I18n.locale).where('tool_translations.name' => name_string)
  end

  private

def self.ransackable_scopes(auth_object = nil)
  %i(with_translated_name)
end

end

app/controllers/admin/tools_controller.rb
class Admin::ToolsController < Admin::AdminController
  before_action :set_tool, only: [:edit, :destroy, :update, :choose, :show]
  def index
    q_param = params[:q]
    page = params[:page]
    per_page = params[:per_page]
    @q = Tool.with_translations(I18n.locale).ransack(q_param)
    @tools = @q.result(distinct: true).page(page).per(per_page)

    @categories = Category.all
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    if @tool.save
      flash[:success]= t('.created')
      redirect_to admin_tool_path(@tool)
    else
      render 'new'
    end
  end

  def show
    @bookings = @tool.books.where('end_date >= ? AND confirmed = ?', Time.now, false) #for more info about this job see jobs/admin/checking.rb
  end

  def choose
  end

  def edit

  end

  def update
    if @tool.update(tool_params)
      if @tool.books.where('end_date >= ?', Time.now).exists?
         @job = Delayed::Job.enqueue Admin::Checking.new(@tool, @tool.books.where('end_date >= ?', Time.now).count)
        # Admin::CheckingJob.perform_now(@tool)
      end
      flash[:success]= t('.edited')
      redirect_to admin_tool_path(@tool)
    else
      render 'edit'
    end
  end

  def destroy
    if @tool.destroy
      flash[:success]= t('.delete')
      redirect_to admin_tools_path
    else
      redirect_to admin_tools_path
    end
  end

  private

  def set_tool
    @tool = Tool.friendly.find(params[:id])
  end


  def tool_params
    params.require(:tool).permit(:photo, :name, :description, :identifier, :quantity, {photos_attributes: [:id, :picture, :tool_id, :_destroy]}, {documentations_attributes: [:id, :name, :file, :tool_id, :_destroy]}, { lab_ids:[]}, { category_ids:[]})
  end
end

app/controllers/technical/tools_controller.rb
class Technical::ToolsController < Technical::TechnicalController
  def index
    q_param = params[:q]
    page = params[:page]
    per_page = params[:per_page]
    lab = params[:lab]
    category = params[:category]
    
    @q = Tool.with_translations(I18n.locale).ransack(q_param)
    @tools = @q.result(distinct: true).page(page).per(per_page).includes(:categories, :labs)

    @categories = Category.all
    @labs = current_technical.labs
  end

  def show
    @tool = Tool.friendly.find(params[:id])
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool, only: [:show]

  def index
    q_param = params[:q]
    page = params[:page]
    per_page = params[:per_page]
    lab = params[:lab]
    category = params[:category]
    @q = Tool.with_translations(I18n.locale).ransack(q_param)
    @tools = @q.result(distinct: true).page(page).per(per_page).includes(:categories, :labs)

    @categories = Category.all
    @labs = Lab.all
  end

  def show
    @posts = @tool.posts
    @tempbook = @tool.tempbooks.build
  end

  private

  def set_tool
    @tool = Tool.friendly.find(params[:id])
  end

end

app/helpers/admin/tools_helper.rb
module Admin::ToolsHelper
end

app/helpers/technical/tools_helper.rb
module Technical::ToolsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/index.html.erb
<h1 class="text-center"> <%= t('shared.menu.tools') %> </h1>
<% if params[:q].present? %>
  <% if params[:q][:categories_name_cont].present? %>
    <h3 class="text-center"> <%= params[:q][:categories_name_cont] %> </h3>
  <% end %>
  <% if params[:q][:labs_name_cont].present? %>
    <h3 class="text-center"> <%= params[:q][:labs_name_cont] %> </h3>
  <% end %>
  <% if params[:q][:translations_name_cont].present? %>
    <h3 class="text-center"> "<%= params[:q][:translations_name_cont] %>" </h3>
  <% end %>
<% end %>

  <div class="row">
    <div class=" col-lg-3 col-md-5">

      <%= link_to t('.newrequest'),  new_request_path, class:"btn btn-outline-primary btn-block" %>
      <br>

      <%= search_form_for @q do |f| %>
        <div class="input-group">
            <%= f.search_field :translations_name_cont, class:"form-control", placeholder: t('.place') %>
            <%= f.submit t('.search'), class:"btn btn-secondary "%>
        </div>
      <% end %>
      <br>

      <div id="accordion" role="tablist">
        <div class="card">
          <div class="card-header" role="tab" id="headingOne">
            <h5 class="mb-0">
              <a data-toggle="collapse" href="#collapseOne" role="button" aria-expanded="false" aria-controls="collapseOne">
                <%= fa_icon('tag') + " " + t('.categories') %>
              </a>
            </h5>
          </div>

          <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
              <% @categories.each do |category| %>
                <%= search_form_for @q do |f| %>
                  <%= f.search_field :categories_name_cont, value: category.name, type:"hidden" %>
                  <td>
                    <%= button_tag type:"submit", class: "btn btn-warning btn-sm btn-block" do %>
                      <%= fa_icon('tag') + " " + category.name %>
                    <% end %>
                  </td>
                <% end %>
                <br>
              <%end%>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header" role="tab" id="headingTwo">
            <h5 class="mb-0">
              <a class="collapsed" data-toggle="collapse" href="#collapseTwo" role="button" aria-expanded="false" aria-controls="collapseTwo">
                <%= fa_icon('flask') + " " + t('.labs') %>
              </a>
            </h5>
          </div>
          <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body">
              <% @labs.each do |lab| %>
                <%= search_form_for @q do |f| %>
                  <%= f.search_field :labs_name_cont, value: lab.name, type:"hidden" %>
                  <td>
                    <%= button_tag type:"submit", class: "btn btn-primary btn-sm btn-block" do %>
                      <%= fa_icon('flask') + " " + lab.name %>
                    <% end %>
                  </td>
                <% end %>
                <hr>
              <%end%>
            </div>
          </div>
        </div>
      </div>

      <br>
      <div class="LI-profile-badge" width="100%" data-version="v1" data-size="medium" data-locale="<%= I18n.locale %>" data-type="horizontal" data-theme="light" data-vanity="davide-fazio"><a class="LI-simple-link" href='https://it.linkedin.com/in/davide-fazio?trk=profile-badge'>Davide F.</a></div>
      <br>
    </div>

    <div class="col-lg-9 col-md-7">
      <div class="row">
        <% @tools.each do |tool| %>
          <% if tool.name.present? %>
            <div class="col-lg-4 col-sm-6 portfolio-item">
              <div class="card h-100">
              <% if tool.photo.standard.present? %>
                <%= link_to image_tag(tool.photo.standard.url, :alt => "toolphoto.jpeg", class:"card-img-top"), tool_path(tool)%>
              <% else %>
                <%= link_to image_tag("generico.png", height: 200, :alt => "toolphoto.jpeg", class:"card-img-top"), tool_path(tool)%>
              <% end %>
                <div class="card-body">
                  <h4 class="card-title">
                    <%= tool.name %>
                  </h4>
                  <p class="card-text text-truncate">
                    <%= tool.description %>
                  </p>
                </div>
                <ul class="list-group list-group-flush">
                  <%= link_to fa_icon('eye') + " " + t('.show'), tool_path(tool), class:"list-group-item list-group-item-primary" %>
                </ul>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <ul class="pagination justify-content-center">
    <%= paginate @tools %>
  </ul>

app/views/tools/show.html.erb
<style>
        .scroll-box {
            overflow-y: scroll;
            height: 200px;
            padding: 1rem
        }
</style>

<h1 class="my-4"> <%= @tool.name %> </h1>
<h3> <%= t('.quantity') + ": " + @tool.quantity.to_s %> </h3>
<br>

<% @tool.reportings.each do |repo| %>
  <div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">  <i class="fa fa-exclamation-triangle">  </i>  <%= " " + t('.warning') %>  </h4>
    <% if I18n.locale.to_s == "en" %>
      <% if repo.quantity == 1 %>
        <p> <%= repo.quantity.to_s + " " %> has been reported due to malfunctions in the <%= " " + repo.lab.name + " " %> laboratory </p>
      <% else %>
        <p> <%= repo.quantity.to_s + " " %> have been reported due to malfunctions in the <%= " " + repo.lab.name + " " %> laboratory </p>
      <% end %>
    <% else %>
      <% if repo.quantity == 1 %>
        <p> <%= repo.quantity.to_s + " " %> è stato segnalato per malfunzionamenti nel laboratorio <%= " " + repo.lab.name + " " %> </p>
      <% else %>
        <p> <%= repo.quantity.to_s + " " %> sono stati segnalati per malfunzionamenti nel laboratorio <%= " " + repo.lab.name + " " %> </p>
      <% end %>
    <% end %>
    <hr>
    <p class="mb-0"> <%= repo.description %> </p>
    <footer class="blockquote-footer">
      <%= t('.technical') %> <cite title="Source Title"> <%= repo.technical.name + " " + repo.technical.surname %>  </cite>
    </footer>
  </div>
<% end %>
<!-- start row -->
<div class="row">
  <!-- start col -->
  <div class="col-lg-8 col-md-7">
    <% if @tool.photo.present? %>
      <a href="#" data-toggle="modal" data-target="#exampleModalLong">
        <%= image_tag(@tool.photo_url, :alt => "toolphoto.jpeg", class:"img-fluid") %>
      </a>
    <% else %>
      <% image_tag("generico.png", :alt => "toolphoto.jpeg", class:"img-fluid") %>
    <% end %>
    <h3 class="my-4"> <%= t('.otherphotos') %> </h3>
    <div class="row">
      <% @tool.photos.each do |photo| %>
        <div class="col-md-3 col-sm-6 mb-4">
          <a href="#" data-toggle="modal" data-target="#exampleModalLong">
            <%= image_tag(photo.picture.standard.url, :alt => "booh", class:"img-fluid") %>
          </a>
        </div>
      <% end %>
    </div>
    <br>
    <br>
    <%= link_to t('.verify'), new_tool_tempbook_path(@tool), class: "btn btn-info btn-block" %>
    <br>
    <br>
    <% if prof_signed_in? && @tool.quantity > 0%>
      <!-- start booking card -->
      <div id="prenota">
        <div class="card">
          <div class="card-header" id="headingTwo">
            <h5 class="mb-0">
              <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                <%=fa_icon('arrow-down') + " " + t('tools.index.book') + "!" %>
              </button>
            </h5>
          </div>
          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#prenota">
            <div class="card-body">
              <%= form_for ([@tool, @tempbook]) do |t|  %>
                <% if @tempbook.errors.any? %>
                  <div id="error_explanation">
                    <% @tempbook.errors.full_messages.each do |message| %>
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <%= message %>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    <% end %>
                  </div>
                <% end %>

                <div class="row">
                  <div class="col-lg-6 ">
                    <div class="form-group" >
                      <%= t.label t('.start') %>
                      <%= t.datetime_local_field :start_date, class:"form-control" %>
                    </div>
                  </div>

                  <div class="col-lg-6">
                    <div class="form-group">
                      <%= t.label t('.end') %>
                      <%= t.datetime_local_field :end_date, class:"form-control" %>
                    </div>
                  </div>
                </div>

<script>
var tzoffset = (new Date()).getTimezoneOffset() * 60000; //offset in milliseconds
var localISOTime = (new Date(Date.now() - tzoffset)).toISOString().slice(0,-1);
var localISOTimeWithoutSeconds = localISOTime.slice(0,16);

// select the "datetime-local" input to set the default value on
var dtlInput = document.querySelector('input[name="tempbook[start_date]"]');
var dtlInputend = document.querySelector('input[name="tempbook[end_date]"]');

// set it and forget it ;)
dtlInput.value = localISOTime.slice(0,16);
dtlInputend.value = localISOTime.slice(0,16);
</script>

                <div class="row">

                  <div class="col-lg-6 ">
                    <div class="form-group">
                      <%= t.label t('requests.new.quantity') %>
                      <%= t.text_field :quantity, value: 1, class:"form-control" %>
                    </div>
                  </div>

                  <div class="col-lg-6">
                    <%= t('.chooselab') %>
                    <% for lab in @tool.labs %>
                      <% if @tool.labs.first == lab %>
                        <div class="input-group">
                          <div class="input-group-prepend">
                            <div class="input-group-text">
                              <%= radio_button_tag "tempbook[lab_id]" , lab.id, true%>
                            </div>
                          </div>
                          <input type="text" class="form-control" aria-label="Text input with checkbox" value="<%= lab.name %>" readonly>
                        </div>
                      <% else %>
                        <div class="input-group">
                          <div class="input-group-prepend">
                            <div class="input-group-text">
                              <%= radio_button_tag "tempbook[lab_id]" , lab.id%>
                            </div>
                          </div>
                          <input type="text" class="form-control" aria-label="Text input with checkbox" value="<%= lab.name %>" readonly>
                        </div>
                      <%end%>
                      <br>
                    <% end %>
                  </div>

                </div>

                <div class="form-group">
                  <%= t.label t('.goal') %>
                  <%= t.text_area :goal, class:"form-control" %>
                </div>

                <%= hidden_field(:tempbook, :prof_id, :value => current_prof.id) %>
                <br>
                <%= t.submit class:"btn btn-success btn-block" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <!-- end booking card -->
    <% end %>
  </div>
  <!-- end col -->
  <!-- start col -->
  <div class="col-lg-4 col-md-5">
    <h3 class="my-3"> <%= t('.description') %> </h3>
    <p> <%= simple_format(@tool.description) %></p>
    <!-- start panel -->
    <div class="row">
      <div class="col-md-4">
        <div class="list-group" id="list-tab" role="tablist">
          <a href="#bookings" data-toggle="tab" class="list-group-item text-center list-group-item-action active" id="bookings-list" aria-controls="bookings">  <%= t('.bookings') %> </a>
          <a href="#documentations" data-toggle="tab" class="list-group-item text-center list-group-item-action" id="docs-list" aria-controls="docs"> <%= t('.documentation') %> </a>
        </div>
      </div>
      <div class="col-md-8">
        <div class="tab-content" id="nav-tabContent">
          <div class="tab-pane fade active scroll-box show border" id="bookings">
            <% if @tool.books.where('end_date >= ? AND confirmed = ?', Time.now, true).present? %>
              <% @tool.books.where('end_date >= ? AND confirmed = ?', Time.now, true).each do |booking| %>
                <%= booking.prof.name + " " + booking.prof.surname %> <br>
                <%= t('.from') + " " %> <b> <%= booking.start_date.strftime("%d/%m/%y %k:%M").to_s + " " %> </b> <br>
                <%= t('.to') + " " %> <b> <%= booking.end_date.strftime("%d/%m/%y %k:%M").to_s %> </b>
                <br>
                <i> <%= t('.quantity') + ": " + booking.quantity.to_s %> </i>
                <hr>
              <%end%>
            <% else %>
              <%= t('.notbooked') %>
            <% end %>
          </div>

          <div class="tab-pane fade scroll-box border" id="documentations">
            <% if @tool.documentations.present? %>
              <% @tool.documentations.each do |doc| %>
                <li class="list-group-item">
                  <%= link_to fa_icon('cloud-download'), doc.file.url %>
                  <%= " " + doc.name %>
                </li>
              <% end %>
            <% else %>
              <%= t('.notdocumented') %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <!-- end panel -->
  </div>
  <!-- end col -->
</div>
<!-- end row -->



<% if @tool.photo.present? %>
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"> <%= @tool.name %> </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= image_tag(@tool.photo_url, :alt => "booh", class:"d-block w-100") %>
            </div>
            <% @tool.photos.each do |photo| %>
              <div class="carousel-item">
                <%= image_tag(photo.picture_url, :alt => "booh", class:"d-block w-100") %>
              </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>




<div class="row">
  <div class="col-lg-9 col-md-7">
    <div class="card my-4">
      <h5 class="card-header"> <%= t('.comment') %> </h5>
      <div class="card-body">
        <%= form_for ([@tool, @tool.posts.build]) do |t|  %>
          <div class="form-group">
            <%= t.text_area :body, class:"form-control" %>
          </div>
          <%= t.submit t('.leavecomment'), class:"btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <% @posts.each do |post| %>
      <% if post.prof.present? %>
        <div class="media mb-4">
          <% if post.prof.picture.present? %>
            <%=image_tag(post.prof.picture_url, :alt => " ", class:"d-flex mr-3 rounded-circle", size: "50x50") %>
          <% else %>
            <%= image_tag("Professor_Farnsworth_50.jpg", :alt => " ", class:"d-flex mr-3 rounded-circle") %>
          <% end %>
          <div class="media-body">
            <h5 class="mt-0">
              <%= post.prof.name + " " + post.prof.surname %>
              <% if prof_signed_in? %>
                <% if current_prof == post.prof %>
                  <%=link_to fa_icon('pencil'), edit_tool_post_path(@tool, post), class:"btn btn-light btn-sm"%> |
                  <%=link_to fa_icon('trash'), tool_post_path(@tool, post), method: :delete, data: {confirm:t('.confirm')}, class:"btn btn-light btn-sm"%>
                <% end %>
              <% end %>
            </h5>
            <% if post.updated_at != post.created_at %>
              <small id="edited" class="form-text text-muted">
                <%= t('.editedat') + " " + post.updated_at.strftime("%d/%m/%y").to_s + " " + t('.at') + " " + post.updated_at.strftime("%H:%M")%>
              </small>
            <% end %>
            <%= simple_format(post.body) %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="col-lg-3 col-md-5">
    <div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="<%= I18n.locale %>" data-type="vertical" data-theme="dark" data-vanity="davide-fazio"><a class="LI-simple-link" href='https://it.linkedin.com/in/davide-fazio?trk=profile-badge'>Davide F.</a></div>
  </div>
</div>