config/routes.rb
Rails.application.routes.draw do

    devise_for :profs, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'profs/omniauth_callbacks'}
    #devise_for :technicals, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'technicals/omniauth_callbacks'}

    scope '(:locale)' do

      devise_for :profs, skip: :omniauth_callbacks, controllers: {
        registrations: 'profs/registrations',
        confirmations: 'profs/confirmations',
      }

      devise_for :technicals, controllers: {
        registrations: 'technicals/registrations',
        confirmations: 'technicals/confirmations',
        sessions: 'technicals/sessions',
      }

      devise_for :admins, controllers: {
        registrations: 'admins/registrations'
      }

      namespace :technical do
        get 'dashboard/index'
        resources :tools, only: [:index, :show] do
          resources :labs, only: [:index] do
            resources :reportings, only: [:new, :create, :show, :edit, :update, :destroy]
          end
        end
        resources :labs, only: [:show]
        resources :reportings, only: [:index]
        resources :requests
        resources :books, only: [:destroy]
      end

      namespace :admin do
        resources :tools do
          resources :documentations, only: [:destroy]
          resources :photos, only: [:destroy]
          resources :books, only: [:index]
        end
        resources :labs do
          resources :lab_technicals, only: [:new, :create, :edit, :update]
        end
        resources :technicals, only: [:index, :show] do
          resources :lab_technicals, only: [:new, :create, :edit, :update]
        end
        resources :requests, only: [:index, :show, :update, :destroy]
        resources :categories
        resources :lab_technicals, only: [:destroy]
        resources :books, only: [:update, :destroy]
        get 'dashboard/index'
        get 'tools/choose/:id(.:format)', :to => 'tools#choose', as: "choose_tool_route"
        get 'labs/assign/:id(.:format)', :to => 'labs#assign', as: "assign_lab_route"
        get 'labs/assign_update/:id/:tool(.:splat)', :to => 'labs#assign_update', as: "assign_update_lab_route"
        post 'authorize/:id(.:format)', :to => 'dashboard#authorize', as: "authorize_route"
        post 'confirm/:id(.:format)', :to => 'dashboard#confirm', as: "confirm_route"
        post 'htmlcreate(.:format)', :to => 'categories#htmlcreate', as: "htmlcreate_route"
        delete 'deleteprof/:id(.:format)', :to => 'dashboard#deleteprof', as: "deleteprof_route"
        post 'reportings/dismiss/:id(.:format)', :to => 'reportings#dismiss', as: "dismiss_route"
        post 'reportings/fix/:id(.:format)', :to => 'reportings#fix', as: "fix_route"
        post 'reportings/replace/:id(.:format)', :to => 'reportings#replace', as: "replace_route"
      end

      post 'avaiable/:tool_id(.:format)', :to => 'tempbooks#avaiable', as: "avaiable_route"
      resources :tools, only: [:index, :show] do
        resources :tempbooks, only: [:new, :create]
        resources :posts, only: [:create, :edit, :update, :destroy]
      end
      resources :categories, only: [:create]
      resources :requests, only: [:new, :create, :index, :show]
      resources :books, only: [:index]

      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
      root to: "home#index"
      #resources :schools
    end
end

app/views/shared/_footer.html.erb
<hr>

<span class="small float-right text-muted">
  <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#donateModal">
    <%= t('.donate') %>
  </button>

  <!-- Modal -->
  <div class="modal fade" id="donateModal" tabindex="-1" role="dialog" aria-labelledby="donateModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="donateModalLabel">  <%= t('.donate') %> </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= link_to fa_icon('paypal') + " PayPal", "http://paypal.me/pools/c/8654CtI2Kj", class:"list-group-item" %>
          <li class="list-group-item">
            <%= fa_icon('btc') %> <textfield id="btc">14vZ781oJrLbiedGik6K5fK6cDjLnMAfe8</textfield>
            <!-- Trigger -->
            <button class="btn btnclipboard" data-clipboard-action="copy" data-clipboard-target="#btc">
                <%= fa_icon('clipboard')%>
            </button>
          </li>
        </div>
      </div>
    </div>
  </div>
</span>

<a href="https://www.iubenda.com/privacy-policy/50660312" class="iubenda-white iubenda-embed " title="Privacy Policy">Privacy Policy</a>
 <script type="text/javascript">
 (function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);
</script>
<script id="CookieDeclaration" src="https://consent.cookiebot.com/bfddb8aa-9b9b-4a70-b748-3654d206ebf7/cd.js" type="text/javascript" async></script>

app/views/shared/_menu.html.erb
<style>
 .navbar {
  position: fixed;
  width: 100%;
  height: 50px;
  z-index: 999;
}
</style>

<b>
  <!-- start desktop navbar -->
  <nav class="navbar navbar-expand-md navbar-dark" style="background-color: rgba(50, 50, 50, 0.7)">
    <a class="navbar-brand" href="/"> <%= fa_icon('home') %> </a>
    <button class="navbar-toggler" type="button" aria-expanded="false" aria-label="Toggle navigation" id="menu-toggle">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto ">

        <li class="nav-item ">
          <!--<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
          <%= link_to  "ITIS", 'http://www.itisetorricelli.it/', target: :_blank, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <% if controller.controller_name == "tools" %>
            <%= link_to t('.tools'), tools_path, class: "nav-link active" %>
          <% else %>
            <%= link_to t('.tools'), tools_path, class: "nav-link" %>
          <% end %>
        </li>

        <% if prof_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownProfs" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon('user-circle') + current_prof.name + " " + current_prof.surname %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownProfs">
              <%= link_to "Account", edit_prof_registration_path, class:"dropdown-item" %>
              <%= link_to t('.bookings'), books_path, class:"dropdown-item" %>
              <%= link_to t('technical.requests.index.requests'), requests_path, class:"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to fa_icon('sign-out') + "Log-out", destroy_prof_session_path, method: :delete, data: { confirm: t('.confirm') }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <% if controller.controller_name == "sessions"%>
              <%= link_to fa_icon('user') + " Prof", new_prof_session_path, class: "nav-link active" %>
            <% else %>
              <%= link_to fa_icon('user') + " Prof", new_prof_session_path, class: "nav-link" %>
            <% end %>
          </li>
        <% end %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= fa_icon('language') + " " + t('.languages') %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <text class="dropdown-item">
              <%= link_to_unless_current image_tag("if_United-Kingdom_92403.ico", size: "28x28") + " English", locale: "en"%>
            </text>
            <text class="dropdown-item">
              <%= link_to_unless_current image_tag("if_Italy_92145.ico", size: "28x28") + " Italiano", locale: "it" %>
            </text>
          </div>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto ">
        <% if admin_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAdmin" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon('cog', class:"fa fa-spin") + " Admin" %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownAdmin">
              <%= link_to "Dashboard", admin_dashboard_index_path, class: "dropdown-item" %>
              <%= link_to "Account", edit_admin_registration_path, class:"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to fa_icon('sign-out') + "Log-out", destroy_admin_session_path, method: :delete, data: { confirm: t('.confirm') }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <% if controller.controller_name == "sessions"%>
              <%= link_to fa_icon('user-secret') + " Admin", admin_dashboard_index_path, class: "nav-link active" %>
            <% else %>
              <%= link_to fa_icon('user-secret') + " Admin", admin_dashboard_index_path, class: "nav-link" %>
            <% end %>
          </li>
        <% end %>

        <% if technical_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownTechnicals" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon('cog', class:"fa fa-spin") + " " + t('.technicals') %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownTechnicals">
              <%= link_to "Dashboard", technical_dashboard_index_path, class: "dropdown-item" %>
              <%= link_to "Account", edit_technical_registration_path, class:"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to fa_icon('sign-out') + "Log-out", destroy_technical_session_path, method: :delete, data: { confirm: t('.confirm') }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <% if controller.controller_name == "sessions"%>
              <%= link_to fa_icon('users') + " " + t('.technicals'), technical_dashboard_index_path, class: "nav-link active" %>
            <% else %>
              <%= link_to fa_icon('users') + " " + t('.technicals'), technical_dashboard_index_path, class: "nav-link" %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <!-- end desktop navbar -->
</b>

<!-- start mobile wrapper -->
<div id="wrapper">
  <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <b>

        <li class="sidebar-brand">
          <a href="/">
            <%= fa_icon('home') + " Home"%>
          </a>
        </li>

        <li>
          <%= link_to fa_icon('graduation-cap') + " ITIS", 'http://www.itisetorricelli.it/', target: :_blank %>
        </li>
        <li>
          <%= link_to fa_icon('wrench') + " " + t('.tools'), tools_path%>
        </li>

        <li>
          <a class=" dropdown-toggle" href="#" id="wrapdrop" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= fa_icon('language') + " " + t('.languages') %>
          </a>
          <div class="dropdown-menu" aria-labelledby="wrapdrop">
            <text class="dropdown-item">
              <%= link_to_unless_current image_tag("if_United-Kingdom_92403.ico", size: "28x28") + " English", locale: "en"%>
            </text>
            <text class="dropdown-item">
              <%= link_to_unless_current image_tag("if_Italy_92145.ico", size: "28x28") + " Italiano", locale: "it" %>
            </text>
          </div>
        </li>

        <% if prof_signed_in? %>
          <li>
            <a class=" dropdown-toggle" href="#" id="navbarDropdownProf" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon('user-circle') + current_prof.name + " " + current_prof.surname %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownProf">
              <%= link_to "Account", edit_prof_registration_path, class:"dropdown-item" %>
              <%= link_to t('.bookings'), books_path, class:"dropdown-item" %>
              <%= link_to t('technical.requests.index.requests'), requests_path, class:"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to fa_icon('sign-out') + "Log-out", destroy_prof_session_path, method: :delete, data: { confirm: t('.confirm') }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li>
            <%= link_to fa_icon('user') + " Prof", new_prof_session_path %>
          </li>
        <% end %>

        <% if admin_signed_in? %>
          <li>
            <a class=" dropdown-toggle" href="#" id="DropdownAdmin" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon('cog') + " Admin" %>
            </a>
            <div class="dropdown-menu" aria-labelledby="DropdownAdmin">
              <%= link_to "Dashboard", admin_dashboard_index_path, class: "dropdown-item" %>
              <%= link_to "Account", edit_admin_registration_path, class:"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to fa_icon('sign-out') + "Log-out", destroy_admin_session_path, method: :delete, data: { confirm: t('.confirm') }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li>
            <%= link_to fa_icon('user-secret') + " Admin", admin_dashboard_index_path%>
          </li>
        <% end %>

        <% if technical_signed_in? %>
          <li>
            <a class=" dropdown-toggle" href="#" id="DropdownTechnical" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon('cog') + " " + t('.technicals') %>
            </a>
            <div class="dropdown-menu" aria-labelledby="DropdownTechnical">
              <%= link_to "Dashboard", technical_dashboard_index_path, class: "dropdown-item" %>
              <%= link_to "Account", edit_technical_registration_path, class:"dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to fa_icon('sign-out') + "Log-out", destroy_technical_session_path, method: :delete, data: { confirm: t('.confirm') }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li>
            <%= link_to fa_icon('users') + " " + t('.technicals'), technical_dashboard_index_path%>
          </li>
        <% end %>
      </b>
    </ul>
  </div>
  <!-- /#sidebar-wrapper -->
</div>
<!-- end mobile wrapper -->





<script>
   $("#menu-toggle").click(function(e) {
       e.preventDefault();
       $("#wrapper").toggleClass("toggled");
   });
   </script>