config/routes.rb
Rails.application.routes.draw do

    devise_for :profs, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'profs/omniauth_callbacks'}
    #devise_for :technicals, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'technicals/omniauth_callbacks'}

    scope '(:locale)' do

      devise_for :profs, skip: :omniauth_callbacks, controllers: {
        registrations: 'profs/registrations',
        confirmations: 'profs/confirmations',
      }

      devise_for :technicals, controllers: {
        registrations: 'technicals/registrations',
        confirmations: 'technicals/confirmations',
        sessions: 'technicals/sessions',
      }

      devise_for :admins, controllers: {
        registrations: 'admins/registrations'
      }

      namespace :technical do
        get 'dashboard/index'
        resources :tools, only: [:index, :show] do
          resources :labs, only: [:index] do
            resources :reportings, only: [:new, :create, :show, :edit, :update, :destroy]
          end
        end
        resources :labs, only: [:show]
        resources :reportings, only: [:index]
        resources :requests
        resources :books, only: [:destroy]
      end

      namespace :admin do
        resources :tools do
          resources :documentations, only: [:destroy]
          resources :photos, only: [:destroy]
          resources :books, only: [:index]
        end
        resources :labs do
          resources :lab_technicals, only: [:new, :create, :edit, :update]
        end
        resources :technicals, only: [:index, :show] do
          resources :lab_technicals, only: [:new, :create, :edit, :update]
        end
        resources :requests, only: [:index, :show, :update, :destroy]
        resources :categories
        resources :lab_technicals, only: [:destroy]
        resources :books, only: [:update, :destroy]
        get 'dashboard/index'
        get 'tools/choose/:id(.:format)', :to => 'tools#choose', as: "choose_tool_route"
        get 'labs/assign/:id(.:format)', :to => 'labs#assign', as: "assign_lab_route"
        get 'labs/assign_update/:id/:tool(.:splat)', :to => 'labs#assign_update', as: "assign_update_lab_route"
        post 'authorize/:id(.:format)', :to => 'dashboard#authorize', as: "authorize_route"
        post 'confirm/:id(.:format)', :to => 'dashboard#confirm', as: "confirm_route"
        post 'htmlcreate(.:format)', :to => 'categories#htmlcreate', as: "htmlcreate_route"
        delete 'deleteprof/:id(.:format)', :to => 'dashboard#deleteprof', as: "deleteprof_route"
        post 'reportings/dismiss/:id(.:format)', :to => 'reportings#dismiss', as: "dismiss_route"
        post 'reportings/fix/:id(.:format)', :to => 'reportings#fix', as: "fix_route"
        post 'reportings/replace/:id(.:format)', :to => 'reportings#replace', as: "replace_route"
      end

      post 'avaiable/:tool_id(.:format)', :to => 'tempbooks#avaiable', as: "avaiable_route"
      resources :tools, only: [:index, :show] do
        resources :tempbooks, only: [:new, :create]
        resources :posts, only: [:create, :edit, :update, :destroy]
      end
      resources :categories, only: [:create]
      resources :requests, only: [:new, :create, :index, :show]
      resources :books, only: [:index]

      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
      root to: "home#index"
      #resources :schools
    end
end

app/models/request.rb
class RequestValidator < ActiveModel::Validator
  def validate(record)
    if record.quantity.present?
      if record.quantity < 0
        record.errors[:base] << I18n.t('tools.quantity')
      end
    end
    if record.money == true && record.approved == false
      record.errors[:base] << I18n.t('request.notmoney')
    end
    if record.arrived == true && (record.approved == false || record.money == false)
      record.errors[:base] << I18n.t('request.notarrived')
    end
  end
end

class Request < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  process_in_background :photo
  validates :name, presence: true
  validates :description, presence: true
  validates :goal, presence: true
  validates :quantity, presence: true, format: {with: /([0-9]+)/}
  has_many :documentations, dependent: :destroy
  accepts_nested_attributes_for :documentations, allow_destroy: true
  has_many :photos, dependent: :destroy
  validates_each :photos do |tool, attr, value|
   tool.errors.add attr, I18n.t('.tools.photos') if tool.photos.size > 4
  end
  accepts_nested_attributes_for :photos, allow_destroy: true
  has_and_belongs_to_many :categories
  belongs_to :prof, optional: true
  belongs_to :technical, optional: true
  before_save :name
  validates_with RequestValidator
  def name=(s)
    write_attribute(:name, s.to_s.capitalize)
  end
end

app/controllers/admin/requests_controller.rb
class Admin::RequestsController < Admin::AdminController
  before_action :set_request, only: [:show, :update, :destroy]

  # there are three types of admins:
  # the role 0 = headmaster, he can approve or delete a new request, so he see only the requests that are not approved
  # the role 1 = dsga, he check if the school have enough money for an approved request, if yes, he order the tool in the request, if not, he reject it, so he see only the requests that are approved
  # the role 2 = ata, when a new tool arrive, he insert it in this system, if the tool was request by someone, he click on button and the tool is automatically created, so he see only the requests that are ordered

  def index
    if current_admin.role == 0
      @requests = Request.where("approved = 'f'")
    elsif current_admin.role == 1
      @requests = Request.where("approved = 't' AND money = 'f'")
    else
      @requests = Request.where("approved = 't' AND money = 't'")
    end
  end

  # a request must made by one prof OR one technical
  def show
    if @request.prof.present?
      @subject = @request.prof
    else
      @subject = @request.technical
    end
  end

  #when an admin click on button, he update the request, the update depends on the request's state

  def update
    if @request.update(request_params)
      if @request.approved == true && @request.money == false
        AdminMailer.request_approved(@request).deliver_later #this email notify at the dsga that a new request was approved
        if @request.prof.present?
          ProfMailer.request_approved(@request.prof, @request).deliver_later #if the request was made by a prof, this email will notify at the prof that his request was approved
        else
          TechnicalMailer.request_approved(@request.technical, @request).deliver_later
        end
      elsif @request.money == true && @request.arrived == false
        AdminMailer.request_money(@request).deliver_later #this email notify at the ata that a new request tool was ordered
        if @request.prof.present?
          ProfMailer.request_money(@request.prof, @request).deliver_later
        else
          TechnicalMailer.request_money(@request.technical, @request).deliver_later
        end
      end
      if @request.arrived == true
        @tool = Tool.new
        @tool.photo = @request.photo
        @tool.name = @request.name
        @tool.description = @request.description
        @tool.quantity = @request.quantity
        @tool.labs << Lab.first
        if @tool.save
          @request.photos.each do |photo|
            @photo = @tool.photos.build
            @photo.picture = photo.picture
            @photo.save
          end
          @request.documentations.each do |document|
            @document = @tool.documentations.build
            @document.name = document.name
            @document.file = document.file
            @document.save
          end
          @request.categories.each do |category|
            @tool.categories << category
          end
          if @request.prof.present?
            ProfMailer.tool_arrived(@request.prof, @tool).deliver_now
          else
            TechnicalMailer.tool_arrived(@request.technical, @tool).deliver_now
          end
          @request.destroy

          flash[:success]= t('.updated')
          redirect_to edit_admin_tool_path(@tool)
        else
          flash[:danger]= 'Oooops'
          redirect_to admin_request_path(@request)
        end
      else
        flash[:success]= t('.updated')
        redirect_to admin_dashboard_index_path
      end
    else
      render 'show'
    end
  end

  def destroy
    if current_admin.role == 0
      if @request.prof.present?
        ProfMailer.request_not_approved(@request.prof, @request).deliver_now
      else
        TechnicalMailer.request_not_approved(@request.technical, @request).deliver_now
      end
    elsif current_admin.role == 1
      if @request.prof.present?
        ProfMailer.request_not_money(@request.prof, @request).deliver_now
      else
        TechnicalMailer.request_not_money(@request.technical, @request).deliver_now
      end
    elsif current_admin.role == 2
      flash[:danger] = t('.cannot')
      redirect_to admin_dashboard_index_path
    end
    @request.destroy
    flash[:success]= t('.deleted')
    redirect_to admin_dashboard_index_path
  end

  private

  def set_request
    @request = Request.find(params[:id])
  end


  def request_params
    params.require(:request).permit(:name, :approved, :money, :arrived, :description, :quantity)
  end
end

app/controllers/admin/technicals_controller.rb
class Admin::TechnicalsController < Admin::AdminController
  before_action :set_technical, only: [:show, :destroy]

  def index
    q_param = params[:q]
    page = params[:page]
    per_page = params[:per_page]
    @q = Technical.order(:id).ransack(q_param)
    @technicals = @q.result(distinct: true).page(page).per(per_page)
  end



  def show
  end


  def destroy
    if @technical.destroy
      flash[:success]= t('.delete')
      redirect_to admin_technicals_path
    else
      redirect_to admin_technicals_path
    end
  end

  private

  def set_technical
    @technical = Technical.find(params[:id])
  end

  def technical_params
    params.require(:technical).permit(:name, :surname, :email, { lab_ids:[]})
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_prof!
  before_action :authorized_prof

  #In this controller, a request can be created by one prof, the entity request can be created by prof and technicals, for technicals the methods are in app/controllers/technical/requests_controller.rb

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    if @request.save
      AdminMailer.new_request(@request).deliver_later #this email notify at the admin that a new request was created
      flash[:primary] = t('.created')
      redirect_to tools_path
    else
      render "new"
    end
  end

  def index
    # the requests have three fields, approved, money and arrived
    # for more information how it work see app/controllers/admin/request_controller.rb
    
    @notapproved = current_prof.requests.where("approved = 'f'")
    @approved = current_prof.requests.where("approved = 't' AND money = 'f'")
    @money = current_prof.requests.where("money = 't'")
  end

  def show
    @request = Request.find(params[:id])
  end

  private

  def request_params
    params.require(:request).permit(:photo, :name, :description, :quantity, :goal, :prof_id, :technical_id, {photos_attributes: [:id, :picture, :tool_id, :request_id, :_destroy]}, {documentations_attributes: [:id, :name, :file, :tool_id, :request_id, :_destroy]}, { category_ids:[]})
  end

end

app/controllers/technical/books_controller.rb
class Technical::BooksController < Technical::TechnicalController

  def destroy
    @booking = Book.find(params[:id])
    if @booking.destroy
      redirect_back(fallback_location:  technical_dashboard_index_path)
    else
      redirect_back(fallback_location:  technical_dashboard_index_path)
    end
  end

end

app/controllers/technical/dashboard_controller.rb
class Technical::DashboardController < Technical::TechnicalController

  def index
    @relations = current_technical.lab_technicals
  end

end

app/controllers/technical/labs_controller.rb
class Technical::LabsController < Technical::TechnicalController

  def index
    @tool = Tool.friendly.find(params[:tool_id])
    @labs = @tool.labs
  end

  def show
    @lab = Lab.friendly.find(params[:id])
    if current_technical.labs.include?(@lab)
      if current_technical.lab_technicals.where("lab_id=?", @lab.id).first.end_date == nil
        @bookings = @lab.books.where("end_date > ? AND confirmed = ?", Time.now, true)
      elsif current_technical.lab_technicals.where("lab_id=?", @lab.id).first.end_date < Time.now
        redirect_back(fallback_location:  technical_dashboard_index_path)
      else
        @bookings = @lab.books.where("end_date > ? AND confirmed = ?", Time.now, true)
      end
    else
      redirect_back(fallback_location:  technical_dashboard_index_path)
    end
  end

end

app/controllers/technical/reportings_controller.rb
class Technical::ReportingsController < Technical::TechnicalController
  before_action :set_reporting, only: [:show, :edit, :update, :destroy]
  before_action :set_variables_and_control, only: [:new, :edit]

  def index
    @reportings = current_technical.reportings
  end

  def new
    @reporting = Reporting.new
  end

  def create
    @reporting = Reporting.new(reporting_params)
    if @reporting.save
      AdminMailer.new_reporting(@reporting).deliver_later
      flash[:primary] = t('.created')
      redirect_to technical_reportings_path
    else
      render action: :new
    end
  end

  def show
  end

  def edit

  end

  def update
    if @reporting.update(reporting_params)
      redirect_to technical_reportings_path
    else
      render 'edit'
    end
  end

  def destroy
    if @reporting.destroy
      flash[:primary] = t('.deleted')
      redirect_to technical_reportings_path
    else
      flash[:danger] = "Oooops"
      redirect_to technical_reportings_path
    end
  end

  private

  def reporting_params
    params.require(:reporting).permit(:tool_id, :lab_id, :technical_id, :description, :quantity)
  end

  def set_reporting
    @reporting = Reporting.find(params[:id])
  end

  def set_variables_and_control
    @tool = Tool.friendly.find(params[:tool_id])
    @lab = Lab.friendly.find(params[:lab_id])
    if current_technical.labs.include?(@lab)
      if current_technical.lab_technicals.where("lab_id=?", @lab.id).first.end_date != nil
        redirect_back(fallback_location:  technical_reportings_path)
        flash[:danger] = t('.notyourlab')
      end
    else
      redirect_back(fallback_location:  technical_reportings_path)
      flash[:danger] = t('.notyourlab')
    end
  end

end

app/controllers/technical/requests_controller.rb
class Technical::RequestsController < Technical::TechnicalController

#for more info about policy of request see controllers/admin/request_controller.rb 

  def index
    @notapproved = current_technical.requests.where("approved = 'f'")
    @approved = current_technical.requests.where("approved = 't' AND money = 'f'")
    @money = current_technical.requests.where("money = 't'")
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    if @request.save
      AdminMailer.new_request(@request).deliver_later
      flash[:primary] = t('.created')
      redirect_to technical_requests_path
    else
      flash[:danger] = "Oooops"
      render 'new'
    end
  end

  def show
    @request = Request.find(params[:id])
  end

  private

  def request_params
    params.require(:request).permit(:photo, :name, :description, :quantity, :goal, :prof_id, :technical_id, {photos_attributes: [:id, :picture, :tool_id, :request_id, :_destroy]}, {documentations_attributes: [:id, :name, :file, :tool_id, :request_id, :_destroy]}, { category_ids:[]})
  end

end

app/controllers/technical/technical_controller.rb
class Technical::TechnicalController < ActionController::Base
    layout 'technical'
    before_action :authenticate_technical!
    before_action :authorized_technical
    before_action :set_i18n_locale_from_params
    # ...

    def authorized_technical
      if current_technical.authorized == false
        flash[:danger] = "Devi essere autorizzato per accedere"
        redirect_to root_path
      end
    end

    protected
      def set_i18n_locale_from_params
        if params[:locale]
          if I18n.available_locales.map(&:to_s).include?(params[:locale])
            I18n.locale = params[:locale]
          else
            flash.now[:notice] = "#{params[:locale]} translation not available"
            logger.error flash.now[:notice]
          end
        end
      end

      def default_url_options
        { locale: I18n.locale }
      end

end

app/controllers/technical/tools_controller.rb
class Technical::ToolsController < Technical::TechnicalController
  def index
    q_param = params[:q]
    page = params[:page]
    per_page = params[:per_page]
    lab = params[:lab]
    category = params[:category]
    
    @q = Tool.with_translations(I18n.locale).ransack(q_param)
    @tools = @q.result(distinct: true).page(page).per(per_page).includes(:categories, :labs)

    @categories = Category.all
    @labs = current_technical.labs
  end

  def show
    @tool = Tool.friendly.find(params[:id])
  end
end

app/helpers/admin/requests_helper.rb
module Admin::RequestsHelper
end

app/helpers/admin/technicals_helper.rb
module Admin::TechnicalsHelper
end

app/views/technical/requests/index.html.erb
<span class="small float-right text-muted">
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= t('.status') %>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <ul class="nav nav-pills">
        <li> <a class="dropdown-item" href="#notapproved" data-toggle="tab"> <%= t('.notapproved') %> </a> </li>
        <li> <a class="dropdown-item" href="#approved" data-toggle="tab"> <%= t('.approved') %> </a> </li>
        <li> <a class="dropdown-item" href="#money" data-toggle="tab"> <%= t('.money') %> </a> </li>
      </ul>
    </div>
  </div>
</span>

<h1> <%= t('.requests') %> <%= link_to t('.new'), new_technical_request_path, class:"btn btn-outline-primary"%> </h1>
<hr>

<div class="panel-body">
  <div class="tab-content">
    <!-- start not approved request -->
    <div class="tab-pane fade in active show" id="notapproved">
      <div class="text-center">
        <h3> <%= t('.notapproved') %> </h3>
      </div>
      <hr>
      <div class="row">
        <% @notapproved.each do |request| %>
          <div class="col-md-3">
            <div class="card">
              <div class="card-header">
                <%= image_tag(request.photo.thumb.url, alt: "Photo") %> <h5 class="card-title"> <%= request.name %> </h5>
              </div>
              <div class="card-body">
                <p class="card-text text-truncate"> <%= request.description %> </p>
                <p class="card-text text-truncate"> <%= request.quantity %> </p>
                <p class="card-text text-truncate"> <%= request.goal %> </p>
              </div>
              <ul class="list-group list-group-flush">
                <%= link_to fa_icon('eye') + " " + t('tools.index.show'), technical_request_path(request), class:"list-group-item list-group-item-warning" %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <!-- end not approved request -->
    <!-- start approved request -->
    <div class="tab-pane fade" id="approved">
      <div class="text-center">
        <h3> <%= t('.approved') %> </h3>
      </div>
      <hr>
      <div class="row">
        <% @approved.each do |request| %>
          <div class="col-md-3">
            <div class="card">
              <div class="card-header">
                <%= image_tag(request.photo.thumb.url, alt: "Photo") %> <h5 class="card-title"><%= request.name %> </h5>
              </div>
              <div class="card-body">
                <p class="card-text text-truncate"> <%= request.description %> </p>
                <p class="card-text text-truncate"> <%= request.quantity %> </p>
                <p class="card-text text-truncate"> <%= request.goal %> </p>
              </div>
              <ul class="list-group list-group-flush">
                <%= link_to fa_icon('eye') + " " + t('tools.index.show'), technical_request_path(request), class:"list-group-item list-group-item-primary" %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <!-- end approved request -->
    <!-- start enough money for request -->
    <div class="tab-pane fade" id="money">
      <div class="text-center">
        <h3> <%= t('.money') %> </h3>
      </div>
      <hr>
      <div class="row">
        <% @money.each do |request| %>
          <div class="col-md-3">
            <div class="card">
              <div class="card-header">
                <%= image_tag(request.photo.thumb.url, alt: "Photo") %> <h5 class="card-title"><%= request.name %> </h5>
              </div>
              <div class="card-body">
                <p class="card-text text-truncate"> <%= request.description %> </p>
                <p class="card-text text-truncate"> <%= request.quantity %> </p>
                <p class="card-text text-truncate"> <%= request.goal %> </p>
              </div>
              <ul class="list-group list-group-flush">
                <%= link_to fa_icon('eye') + " " + t('tools.index.show'), technical_request_path(request), class:"list-group-item list-group-item-success" %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <!-- end enough money for request -->
  </div>
</div>

app/views/technical/requests/new.html.erb
<h1><%= t('requests.new.new') %></h1>
<hr>

<%= form_for ([:technical, @request])  do |t|  %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <% @request.errors.full_messages.each do |message| %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4 col-sm-6">
      <img height="150" width="200" id="image" />
    </div>
    <div class="col-md-8 col-sm-6">
      <div class="custom-file">
        <%= t.label t('admin.tools.form.photo'), class:"custom-file-label" %>
        <%= t.file_field :photo, class:"custom-file-input" %>
      </div>
    </div>
  </div>

  <div class="form-group" >
    <%= t.label t('admin.tools.form.name') %>
    <%= t.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= t.label t('admin.tools.form.description') %>
    <%= t.text_area :description, class:"form-control" %>
  </div>

  <div class="row">
    <div class="col-md-6 col-sm-6">
      <div class="form-group">
        <%= t.label t('tools.show.goal') %>
        <%= t.text_area :goal, class:"form-control" %>
      </div>
    </div>
    <div class="col-md-6 col-sm-6">
      <div class="form-group">
        <%= t.label t('requests.new.quantity') %>
        <%= t.text_field :quantity, class:"form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 col-sm-6">
      <div class="form-group">
        <%= t.nested_fields_for :photos do |d| %>
          <%= d.remove_nested_fields_link t('admin.tools.form.photoremove'), data: { confirm: t('admin.tools.index.confirm') } %>
          <br>
          <%= d.file_field :picture %>
        <% end %>
        <%= t.add_nested_fields_link :photos, t('admin.tools.form.photoadd') %>
      </div>
    </div>
    <div class="col-md-6 col-sm-6">
      <div class="form-group">
        <%= t.nested_fields_for :documentations do |d| %>
          <%= d.remove_nested_fields_link t('admin.tools.form.docremove'), data: { confirm: t('admin.tools.index.confirm') } %>
          <br>
          <%= d.label t('admin.tools.form.docname') %>
          <%= d.text_field :name, class:"form-control" %>
          <%= d.file_field :file %>
          <small class="form-text text-muted"> <%= t('admin.tools.form.docwarn') %> </small>
        <% end %>
        <%= t.add_nested_fields_link :documentations, t('admin.tools.form.docadd') %>
      </div>
    </div>
  </div>

  <%= t.label t('admin.tools.form.categorychoose') %>
  <%= t.select :category_ids, Category.all.pluck(:name, :id), {}, { multiple: true, class: "selectize" } %>

  <hr>

  <%= hidden_field(:request, :technical_id, :value => current_technical.id) %>

  <%= t.submit class:"btn btn-primary btn-block"%>

<script>

document.getElementById("request_photo").onchange = function () {
    var reader = new FileReader();

    reader.onload = function (e) {
        // get loaded data and render thumbnail.
        document.getElementById("image").src = e.target.result;
    };

    // read the image file as a data URL.
    reader.readAsDataURL(this.files[0]);
};


</script>


<% end %>



<!-- Modal -->
<div class="modal fade category-modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"> <%= t('admin.categories.index.new') %> </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <%= form_for Category.new do |t|  %>
          <div class="form-group">
            <%= t.label t('admin.tools.form.name') %>
            <%= t.text_field :name, class:"form-control" %>
          </div>
          <%= t.submit class:"btn btn-primary btn-block"%>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/technical/requests/show.html.erb
<div class="row">
  <div class="col-md-4 col-sm-4">
    <h2 class="my-4"> <%= @request.name %> </h2>
  </div>
  <div class="col-md-4 col-sm-4">
    <h2 class="my-4"> <%= t('tools.show.quantity') + ": " + @request.quantity.to_s %> </h2>
  </div>
  <div class="col-md-4 col-sm-4">
    <% if @request.approved == false %>
      <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
        <div class="card-header"> <h2> <%= t('.noapproved') %> </h2> </div>
      </div>
    <% elsif @request.money == false %>
      <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
        <div class="card-header"> <h2> <%= t('.approved') %> </h2> </div>
      </div>
    <% else %>
      <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
        <div class="panel-header"> <h2> <%= t('.money') %> </h2> </div>
      </div>
    <% end %>
  </div>
</div>
<br>


<div class="row">
  <div class="col-lg-8 col-md-7">
    <% if @request.photo.present? %>
      <a href="#" data-toggle="modal" data-target="#exampleModalLong">
        <%= image_tag(@request.photo_url, :alt => "toolphoto.jpeg", class:"img-fluid") %>
      </a>
    <% else %>
      <% image_tag("standard_toolphoto.jpeg", :alt => "toolphoto.jpeg", class:"img-fluid") %>
    <% end %>
    <br>
    <br>
    <p> <%= simple_format(@request.goal) %> </p>
    <hr>
  </div>
  <div class="col-lg-4 col-md-5">
    <h3 class="my-3"> <%= t('tools.show.description') %> </h3>
    <p> <%= simple_format(@request.description) %></p>
    <ul class="list-group">
      <% @request.documentations.each do |doc| %>
        <li class="list-group-item">
          <%= link_to fa_icon('cloud-download'), doc.file.url %>
          <%= " " + doc.name + " " %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<h3 class="my-4"> <%= t('tools.show.otherphotos') %> </h3>
<div class="row">
  <% @request.photos.each do |photo| %>
    <div class="col-md-3 col-sm-6 mb-4">
      <a href="#" data-toggle="modal" data-target="#exampleModalLong">
        <%= image_tag(photo.picture.standard.url, :alt => "booh", class:"img-fluid") %>
      </a>
    </div>
  <% end %>
</div>

<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"> <%= @request.name %> </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= image_tag(@request.photo_url, :alt => "booh", class:"d-block w-100") %>
            </div>
            <% @request.photos.each do |photo| %>
              <div class="carousel-item">
                <%= image_tag(photo.picture_url, :alt => "booh", class:"d-block w-100") %>
              </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>